name: Build and Deploy to CapRover

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to `deploy` branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git clone --branch deploy https://github.com/${{ github.repository }} deploy
        rm -rf deploy/*
        cp -r dist deploy/
        cp captain-definition deploy/

        cd deploy
        git add .
        git commit -m "Deploy from main @ $GITHUB_SHA"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin deploy --force
